"""
Atualiza apenas a coluna Descricao no album.csv e na planilha Google Sheets.
Preserva Status e Repetidas intactos.

Uso:
  python atualizar_descricoes.py
"""
import csv
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

BASE = os.path.dirname(os.path.abspath(__file__))

DESCRICOES = {
    # ── Abertura / FWC ──────────────────────────────────────────────────────
    "00":    "Logo Panini",
    "FWC1":  "Emblema Oficial FOIL",
    "FWC2":  "Emblema Oficial FOIL",
    "FWC3":  "Mascotes Oficiais FOIL",
    "FWC4":  "Slogan Oficial FOIL",
    "FWC5":  "Bola Oficial FOIL",
    "FWC6":  "Canadá — Países e Cidades Sede FOIL",
    "FWC7":  "México — Países e Cidades Sede FOIL",
    "FWC8":  "EUA — Países e Cidades Sede FOIL",
    "FWC9":  "Itália 1934 — Museu FIFA FOIL",
    "FWC10": "Uruguai 1950 — Museu FIFA FOIL",
    "FWC11": "Alemanha Ocidental 1954 — Museu FIFA FOIL",
    "FWC12": "Brasil 1962 — Museu FIFA FOIL",
    "FWC13": "Alemanha Ocidental 1974 — Museu FIFA FOIL",
    "FWC14": "Argentina 1986 — Museu FIFA FOIL",
    "FWC15": "Brasil 1994 — Museu FIFA FOIL",
    "FWC16": "Brasil 2002 — Museu FIFA FOIL",
    "FWC17": "Itália 2006 — Museu FIFA FOIL",
    "FWC18": "Alemanha 2014 — Museu FIFA FOIL",
    "FWC19": "Argentina 2022 — Museu FIFA FOIL",
    # ── Algeria (ALG) ───────────────────────────────────────────────────────
    "ALG1":  "Escudo FOIL",
    "ALG2":  "Alexis Guendouz",
    "ALG3":  "Ramy Bensebaini",
    "ALG4":  "Youcef Atal",
    "ALG5":  "Rayan Aït-Nouri",
    "ALG6":  "Mohamed Amine Tougai",
    "ALG7":  "Aïssa Mandi",
    "ALG8":  "Ismael Bennacer",
    "ALG9":  "Houssem Aquar",
    "ALG10": "Hicham Boudaoui",
    "ALG11": "Ramiz Zerrouki",
    "ALG12": "Nabil Bentalab",
    "ALG13": "Foto do Time",
    "ALG14": "Farés Chaibi",
    "ALG15": "Riyad Mahrez",
    "ALG16": "Said Benrahma",
    "ALG17": "Anis Hadj Moussa",
    "ALG18": "Amine Gouiri",
    "ALG19": "Baghdad Bounedjah",
    "ALG20": "Mohammed Amoura",
    # ── Argentina (ARG) ─────────────────────────────────────────────────────
    "ARG1":  "Escudo FOIL",
    "ARG2":  "Emiliano Martínez",
    "ARG3":  "Nahuel Molina",
    "ARG4":  "Cristian Romero",
    "ARG5":  "Nicolás Otamendi",
    "ARG6":  "Nicolás Tagliafico",
    "ARG7":  "Leonardo Balerdi",
    "ARG8":  "Enzo Fernández",
    "ARG9":  "Alexis Mac Allister",
    "ARG10": "Rodrigo De Paul",
    "ARG11": "Exequiel Palacios",
    "ARG12": "Leandro Paredes",
    "ARG13": "Foto do Time",
    "ARG14": "Nico Paz",
    "ARG15": "Franco Mastantuono",
    "ARG16": "Nico González",
    "ARG17": "Lionel Messi",
    "ARG18": "Lautaro Martínez",
    "ARG19": "Julián Álvarez",
    "ARG20": "Giuliano Simeone",
    # ── Australia (AUS) ─────────────────────────────────────────────────────
    "AUS1":  "Escudo FOIL",
    "AUS2":  "Mathew Ryan",
    "AUS3":  "Joe Gauci",
    "AUS4":  "Harry Souttar",
    "AUS5":  "Alessandro Circati",
    "AUS6":  "Jordan Bos",
    "AUS7":  "Aziz Behich",
    "AUS8":  "Cameron Burgess",
    "AUS9":  "Lewis Miller",
    "AUS10": "Milos Degenek",
    "AUS11": "Jackson Irvine",
    "AUS12": "Riley McGree",
    "AUS13": "Foto do Time",
    "AUS14": "Aiden O'Neill",
    "AUS15": "Connor Metcalfe",
    "AUS16": "Patrick Yazbek",
    "AUS17": "Craig Goodwin",
    "AUS18": "Kusini Yengi",
    "AUS19": "Nestory Irankunda",
    "AUS20": "Mohamed Touré",
    # ── Austria (AUT) ───────────────────────────────────────────────────────
    "AUT1":  "Escudo FOIL",
    "AUT2":  "Alexander Schlager",
    "AUT3":  "Patrick Pentz",
    "AUT4":  "David Alaba",
    "AUT5":  "Kevin Danso",
    "AUT6":  "Philipp Lienhart",
    "AUT7":  "Stefan Posch",
    "AUT8":  "Phillipp Mwene",
    "AUT9":  "Alexander Prass",
    "AUT10": "Xaver Schlager",
    "AUT11": "Marcel Sabitzer",
    "AUT12": "Konrad Laimer",
    "AUT13": "Foto do Time",
    "AUT14": "Florian Grillitsch",
    "AUT15": "Nicolas Seiwald",
    "AUT16": "Romano Schmid",
    "AUT17": "Patrick Wimmer",
    "AUT18": "Christoph Baumgartner",
    "AUT19": "Michael Gregoritsch",
    "AUT20": "Marko Arnautović",
    # ── Belgium (BEL) ───────────────────────────────────────────────────────
    "BEL1":  "Escudo FOIL",
    "BEL2":  "Thibaut Courtois",
    "BEL3":  "Arthur Theate",
    "BEL4":  "Timothy Castagne",
    "BEL5":  "Zeno Debast",
    "BEL6":  "Brandon Mechele",
    "BEL7":  "Maxim De Cuyper",
    "BEL8":  "Thomas Meunier",
    "BEL9":  "Youri Tielemans",
    "BEL10": "Amadou Onana",
    "BEL11": "Nicolas Raskin",
    "BEL12": "Alexis Saelemaekers",
    "BEL13": "Foto do Time",
    "BEL14": "Hans Vanaken",
    "BEL15": "Kevin De Bruyne",
    "BEL16": "Jérémy Doku",
    "BEL17": "Charles De Ketelaere",
    "BEL18": "Leandro Trossard",
    "BEL19": "Loïs Openda",
    "BEL20": "Romelu Lukaku",
    # ── Bosnia (BIH) ────────────────────────────────────────────────────────
    "BIH1":  "Escudo FOIL",
    "BIH2":  "Nikola Vasilj",
    "BIH3":  "Amer Dedic",
    "BIH4":  "Sead Kolašinac",
    "BIH5":  "Tarik Muharemovic",
    "BIH6":  "Nihad Mujakic",
    "BIH7":  "Nikola Katic",
    "BIH8":  "Amir Hadziahmetovic",
    "BIH9":  "Benjamin Tahirovic",
    "BIH10": "Armin Gigovic",
    "BIH11": "Ivan Šunjić",
    "BIH12": "Ivan Bašić",
    "BIH13": "Foto do Time",
    "BIH14": "Dzenis Burnic",
    "BIH15": "Esmir Bajraktarevic",
    "BIH16": "Amar Memic",
    "BIH17": "Ermedin Demirovic",
    "BIH18": "Edin Džeko",
    "BIH19": "Samed Bazdar",
    "BIH20": "Haris Tabakovic",
    # ── Brazil (BRA) ────────────────────────────────────────────────────────
    "BRA1":  "Escudo FOIL",
    "BRA2":  "Alisson",
    "BRA3":  "Bento",
    "BRA4":  "Marquinhos",
    "BRA5":  "Éder Militão",
    "BRA6":  "Gabriel Magalhães",
    "BRA7":  "Danilo",
    "BRA8":  "Wesley",
    "BRA9":  "Lucas Paquetá",
    "BRA10": "Casemiro",
    "BRA11": "Bruno Guimarães",
    "BRA12": "Luiz Henrique",
    "BRA13": "Foto do Time",
    "BRA14": "Vinícius Júnior",
    "BRA15": "Rodrygo",
    "BRA16": "João Pedro",
    "BRA17": "Matheus Cunha",
    "BRA18": "Gabriel Martinelli",
    "BRA19": "Raphinha",
    "BRA20": "Estêvão",
    # ── Canada (CAN) ────────────────────────────────────────────────────────
    "CAN1":  "Escudo FOIL",
    "CAN2":  "Dayne St. Clair",
    "CAN3":  "Alphonso Davies",
    "CAN4":  "Alistair Johnston",
    "CAN5":  "Samuel Adekugbe",
    "CAN6":  "Richie Laryea",
    "CAN7":  "Derek Cornelius",
    "CAN8":  "Moïse Bombito",
    "CAN9":  "Kamal Miller",
    "CAN10": "Stephen Eustáquio",
    "CAN11": "Ismaël Koné",
    "CAN12": "Jonathan Osorio",
    "CAN13": "Foto do Time",
    "CAN14": "Jacob Shaffelburg",
    "CAN15": "Mathieu Choinière",
    "CAN16": "Niko Sigur",
    "CAN17": "Tajon Buchanan",
    "CAN18": "Liam Millar",
    "CAN19": "Cyle Larin",
    "CAN20": "Jonathan David",
    # ── Cape Verde (CPV) ────────────────────────────────────────────────────
    "CPV1":  "Escudo FOIL",
    "CPV2":  "Vozinha",
    "CPV3":  "Logan Costa",
    "CPV4":  "Pico",
    "CPV5":  "Diney",
    "CPV6":  "Steven Moreira",
    "CPV7":  "Wagner Pina",
    "CPV8":  "João Paulo",
    "CPV9":  "Yannick Semedo",
    "CPV10": "Kevin Pina",
    "CPV11": "Patrick Andrade",
    "CPV12": "Jamiro Monteiro",
    "CPV13": "Foto do Time",
    "CPV14": "Deroy Duarte",
    "CPV15": "Garry Rodrigues",
    "CPV16": "Jovane Cabral",
    "CPV17": "Ryan Mendes",
    "CPV18": "Dailon Livramento",
    "CPV19": "Willy Semedo",
    "CPV20": "Bebé",
    # ── Ivory Coast (CIV) ───────────────────────────────────────────────────
    "CIV1":  "Escudo FOIL",
    "CIV2":  "Yahia Fofana",
    "CIV3":  "Ghislain Konan",
    "CIV4":  "Wilfried Singo",
    "CIV5":  "Odilon Kossounou",
    "CIV6":  "Evan Ndicka",
    "CIV7":  "Willy Boly",
    "CIV8":  "Emmanuel Agbadou",
    "CIV9":  "Ousmane Diomandé",
    "CIV10": "Franck Kessié",
    "CIV11": "Seko Fofana",
    "CIV12": "Ibrahim Sangaré",
    "CIV13": "Foto do Time",
    "CIV14": "Jean-Philippe Gbamin",
    "CIV15": "Amad Diallo",
    "CIV16": "Sébastien Haller",
    "CIV17": "Simon Adingra",
    "CIV18": "Yan Diomandé",
    "CIV19": "Evann Guessand",
    "CIV20": "Oumar Diakité",
    # ── Congo DR (COD) ──────────────────────────────────────────────────────
    "COD1":  "Escudo FOIL",
    "COD2":  "Lionel Mpasi",
    "COD3":  "Aaron Wan-Bissaka",
    "COD4":  "Axel Tuanzebe",
    "COD5":  "Arthur Masuaku",
    "COD6":  "Chancel Mbemba",
    "COD7":  "Joris Kayembe",
    "COD8":  "Charles Pickel",
    "COD9":  "Ngal'ayel Mukau",
    "COD10": "Edo Kayembe",
    "COD11": "Samuel Moutoussamy",
    "COD12": "Noah Sadiki",
    "COD13": "Foto do Time",
    "COD14": "Théo Bongonda",
    "COD15": "Meschak Elia",
    "COD16": "Yoane Wissa",
    "COD17": "Brian Cipenga",
    "COD18": "Fiston Mayele",
    "COD19": "Cédric Bakambu",
    "COD20": "Nathanaël Mbuku",
    # ── Colombia (COL) ──────────────────────────────────────────────────────
    "COL1":  "Escudo FOIL",
    "COL2":  "Camilo Vargas",
    "COL3":  "David Ospina",
    "COL4":  "Dávinson Sánchez",
    "COL5":  "Yerry Mina",
    "COL6":  "Daniel Muñoz",
    "COL7":  "Johan Mojica",
    "COL8":  "Jhon Lucumí",
    "COL9":  "Santiago Arias",
    "COL10": "Jefferson Lerma",
    "COL11": "Kevin Castaño",
    "COL12": "Richard Ríos",
    "COL13": "Foto do Time",
    "COL14": "James Rodríguez",
    "COL15": "Juan Fernando Quintero",
    "COL16": "Jorge Carrascal",
    "COL17": "Jon Arias",
    "COL18": "Jhon Córdoba",
    "COL19": "Luis Suárez",
    "COL20": "Luis Díaz",
    # ── Croatia (CRO) ───────────────────────────────────────────────────────
    "CRO1":  "Escudo FOIL",
    "CRO2":  "Dominik Livaković",
    "CRO3":  "Duje Ćaleta-Car",
    "CRO4":  "Joško Gvardiol",
    "CRO5":  "Josip Stanišić",
    "CRO6":  "Luka Vušković",
    "CRO7":  "Josip Šutalo",
    "CRO8":  "Kristijan Jakić",
    "CRO9":  "Luka Modrić",
    "CRO10": "Mateo Kovačić",
    "CRO11": "Martin Baturina",
    "CRO12": "Lovro Majer",
    "CRO13": "Foto do Time",
    "CRO14": "Mario Pašalić",
    "CRO15": "Petar Sučić",
    "CRO16": "Ivan Perišić",
    "CRO17": "Marco Pašalić",
    "CRO18": "Ante Budimir",
    "CRO19": "Andrej Kramarić",
    "CRO20": "Franjo Ivanović",
    # ── Curaçao (CUW) ───────────────────────────────────────────────────────
    "CUW1":  "Escudo FOIL",
    "CUW2":  "Eloy Room",
    "CUW3":  "Armando Obispo",
    "CUW4":  "Sherel Floranus",
    "CUW5":  "Jurien Gaari",
    "CUW6":  "Joshua Brenet",
    "CUW7":  "Roshon Van Eijma",
    "CUW8":  "Shurandy Sambo",
    "CUW9":  "Livano Comenencia",
    "CUW10": "Godfried Roemeratoe",
    "CUW11": "Juninho Bacuna",
    "CUW12": "Leandro Bacuna",
    "CUW13": "Foto do Time",
    "CUW14": "Tahith Chong",
    "CUW15": "Kenji Gorre",
    "CUW16": "Jearl Margaritha",
    "CUW17": "Jurgen Locadia",
    "CUW18": "Jeremy Antonisse",
    "CUW19": "Gervane Kastaneer",
    "CUW20": "Sontje Hansen",
    # ── Czechia (CZE) ───────────────────────────────────────────────────────
    "CZE1":  "Escudo FOIL",
    "CZE2":  "Matej Kovář",
    "CZE3":  "Jindřich Staněk",
    "CZE4":  "Ladislav Krejčí",
    "CZE5":  "Vladimír Coufal",
    "CZE6":  "Jaroslav Zelený",
    "CZE7":  "Tomáš Holeš",
    "CZE8":  "David Zima",
    "CZE9":  "Michal Sadílek",
    "CZE10": "Lukáš Provod",
    "CZE11": "Lukáš Červ",
    "CZE12": "Tomáš Souček",
    "CZE13": "Foto do Time",
    "CZE14": "Pavel Šulc",
    "CZE15": "Matěj Vydra",
    "CZE16": "Vasil Kušej",
    "CZE17": "Tomáš Chorý",
    "CZE18": "Václav Černý",
    "CZE19": "Adam Hložek",
    "CZE20": "Patrik Schick",
    # ── Ecuador (ECU) ───────────────────────────────────────────────────────
    "ECU1":  "Escudo FOIL",
    "ECU2":  "Hernán Galíndez",
    "ECU3":  "Gonzalo Valle",
    "ECU4":  "Piero Hincapié",
    "ECU5":  "Pervis Estupiñán",
    "ECU6":  "Willian Pacho",
    "ECU7":  "Ángelo Preciado",
    "ECU8":  "Joel Ordóñez",
    "ECU9":  "Moisés Caicedo",
    "ECU10": "Alan Franco",
    "ECU11": "Kendry Páez",
    "ECU12": "Pedro Vite",
    "ECU13": "Foto do Time",
    "ECU14": "John Yeboah",
    "ECU15": "Leonardo Campana",
    "ECU16": "Gonzalo Plata",
    "ECU17": "Nilson Angulo",
    "ECU18": "Alan Minda",
    "ECU19": "Kevin Rodríguez",
    "ECU20": "Enner Valencia",
    # ── Egypt (EGY) ─────────────────────────────────────────────────────────
    "EGY1":  "Escudo FOIL",
    "EGY2":  "Mohamed El-Shenawy",
    "EGY3":  "Mohamed Hany",
    "EGY4":  "Mohamed Hamdy",
    "EGY5":  "Yasser Ibrahim",
    "EGY6":  "Khaled Sobhy",
    "EGY7":  "Ramy Rabia",
    "EGY8":  "Hossam Abdelmaguid",
    "EGY9":  "Ahmed Fatouh",
    "EGY10": "Marwan Attia",
    "EGY11": "Zizo",
    "EGY12": "Hamdy Fathy",
    "EGY13": "Foto do Time",
    "EGY14": "Mohamed Lasheen",
    "EGY15": "Emam Ashour",
    "EGY16": "Osama Faisal",
    "EGY17": "Mohamed Salah",
    "EGY18": "Mostafa Mohamed",
    "EGY19": "Trezeguet",
    "EGY20": "Omar Marmoush",
    # ── England (ENG) ───────────────────────────────────────────────────────
    "ENG1":  "Escudo FOIL",
    "ENG2":  "Jordan Pickford",
    "ENG3":  "John Stones",
    "ENG4":  "Marc Guéhi",
    "ENG5":  "Ezri Konsa",
    "ENG6":  "Trent Alexander-Arnold",
    "ENG7":  "Reece James",
    "ENG8":  "Dan Burn",
    "ENG9":  "Jordan Henderson",
    "ENG10": "Declan Rice",
    "ENG11": "Jude Bellingham",
    "ENG12": "Cole Palmer",
    "ENG13": "Foto do Time",
    "ENG14": "Morgan Rogers",
    "ENG15": "Anthony Gordon",
    "ENG16": "Phil Foden",
    "ENG17": "Bukayo Saka",
    "ENG18": "Harry Kane",
    "ENG19": "Marcus Rashford",
    "ENG20": "Ollie Watkins",
    # ── Spain (ESP) ─────────────────────────────────────────────────────────
    "ESP1":  "Escudo FOIL",
    "ESP2":  "Unai Simón",
    "ESP3":  "Robin Le Normand",
    "ESP4":  "Aymeric Laporte",
    "ESP5":  "Dean Huijsen",
    "ESP6":  "Pedro Porro",
    "ESP7":  "Dani Carvajal",
    "ESP8":  "Marc Cucurella",
    "ESP9":  "Martín Zubimendi",
    "ESP10": "Rodri",
    "ESP11": "Pedri",
    "ESP12": "Fabián Ruiz",
    "ESP13": "Foto do Time",
    "ESP14": "Mikel Merino",
    "ESP15": "Lamine Yamal",
    "ESP16": "Dani Olmo",
    "ESP17": "Nico Williams",
    "ESP18": "Ferran Torres",
    "ESP19": "Álvaro Morata",
    "ESP20": "Mikel Oyarzabal",
    # ── France (FRA) ────────────────────────────────────────────────────────
    "FRA1":  "Escudo FOIL",
    "FRA2":  "Mike Maignan",
    "FRA3":  "Theo Hernández",
    "FRA4":  "William Saliba",
    "FRA5":  "Jules Koundé",
    "FRA6":  "Ibrahima Konaté",
    "FRA7":  "Dayot Upamecano",
    "FRA8":  "Lucas Digne",
    "FRA9":  "Aurélien Tchouaméni",
    "FRA10": "Eduardo Camavinga",
    "FRA11": "Manu Koné",
    "FRA12": "Adrien Rabiot",
    "FRA13": "Foto do Time",
    "FRA14": "Michael Olise",
    "FRA15": "Ousmane Dembélé",
    "FRA16": "Bradley Barcola",
    "FRA17": "Désiré Doué",
    "FRA18": "Kingsley Coman",
    "FRA19": "Hugo Ekitiké",
    "FRA20": "Kylian Mbappé",
    # ── Germany (GER) ───────────────────────────────────────────────────────
    "GER1":  "Escudo FOIL",
    "GER2":  "Marc-André ter Stegen",
    "GER3":  "Jonathan Tah",
    "GER4":  "David Raum",
    "GER5":  "Nico Schlotterbeck",
    "GER6":  "Antonio Rüdiger",
    "GER7":  "Waldemar Anton",
    "GER8":  "Ridle Baku",
    "GER9":  "Maximilian Mittelstädt",
    "GER10": "Joshua Kimmich",
    "GER11": "Florian Wirtz",
    "GER12": "Felix Nmecha",
    "GER13": "Foto do Time",
    "GER14": "Leon Goretzka",
    "GER15": "Jamal Musiala",
    "GER16": "Serge Gnabry",
    "GER17": "Kai Havertz",
    "GER18": "Leroy Sané",
    "GER19": "Karim Adeyemi",
    "GER20": "Nick Woltemade",
    # ── Ghana (GHA) ─────────────────────────────────────────────────────────
    "GHA1":  "Escudo FOIL",
    "GHA2":  "Lawrence Ati-Zigi",
    "GHA3":  "Tariq Lamptey",
    "GHA4":  "Mohammed Salisu",
    "GHA5":  "Alidu Seidu",
    "GHA6":  "Alexander Djiku",
    "GHA7":  "Gideon Mensah",
    "GHA8":  "Caleb Yirenkyi",
    "GHA9":  "Abdul Fatawu Issahaku",
    "GHA10": "Thomas Partey",
    "GHA11": "Salis Abdul Samed",
    "GHA12": "Kamaldeen Sulemana",
    "GHA13": "Foto do Time",
    "GHA14": "Mohammed Kudus",
    "GHA15": "Iñaki Williams",
    "GHA16": "Jordan Ayew",
    "GHA17": "André Ayew",
    "GHA18": "Joseph Paintsil",
    "GHA19": "Osman Bukari",
    "GHA20": "Antoine Semenyo",
    # ── Haiti (HAI) ─────────────────────────────────────────────────────────
    "HAI1":  "Escudo FOIL",
    "HAI2":  "Johny Placide",
    "HAI3":  "Carlens Arcus",
    "HAI4":  "Martin Expérience",
    "HAI5":  "Jean-Kevin Duverne",
    "HAI6":  "Ricardo Adé",
    "HAI7":  "Duke Lacroix",
    "HAI8":  "Garven Metusala",
    "HAI9":  "Hannes Delcroix",
    "HAI10": "Leverton Pierre",
    "HAI11": "Danley Jean Jacques",
    "HAI12": "Jean-Ricner Bellegarde",
    "HAI13": "Foto do Time",
    "HAI14": "Christopher Attys",
    "HAI15": "Derrick Etienne Jr.",
    "HAI16": "Josue Casimir",
    "HAI17": "Ruben Providence",
    "HAI18": "Duckens Nazon",
    "HAI19": "Louicius Deedson",
    "HAI20": "Frantzdy Pierrot",
    # ── Iran (IRN) ──────────────────────────────────────────────────────────
    "IRN1":  "Escudo FOIL",
    "IRN2":  "Alireza Beiranvand",
    "IRN3":  "Morteza Pouraliganji",
    "IRN4":  "Ehsan Hajsafi",
    "IRN5":  "Milad Mohammadi",
    "IRN6":  "Shojae Khalilzadeh",
    "IRN7":  "Ramin Rezaeian",
    "IRN8":  "Hossein Kanaani",
    "IRN9":  "Sadegh Moharrami",
    "IRN10": "Saleh Hardani",
    "IRN11": "Saeed Ezatolahi",
    "IRN12": "Saman Ghoddos",
    "IRN13": "Foto do Time",
    "IRN14": "Omid Noorafkan",
    "IRN15": "Roozbeh Cheshmi",
    "IRN16": "Mohammad Mohebi",
    "IRN17": "Sardar Azmoun",
    "IRN18": "Mehdi Taremi",
    "IRN19": "Alireza Jahanbakhsh",
    "IRN20": "Ali Gholizadeh",
    # ── Iraq (IRQ) ──────────────────────────────────────────────────────────
    "IRQ1":  "Escudo FOIL",
    "IRQ2":  "Jalal Hassan",
    "IRQ3":  "Rebin Sulaka",
    "IRQ4":  "Hussein Ali",
    "IRQ5":  "Akam Hashem",
    "IRQ6":  "Merchas Doski",
    "IRQ7":  "Zaid Tahseen",
    "IRQ8":  "Manaf Younis",
    "IRQ9":  "Zidane Iqbal",
    "IRQ10": "Amir Al-Ammari",
    "IRQ11": "Ibrahim Bayesh",
    "IRQ12": "Ali Jasim",
    "IRQ13": "Foto do Time",
    "IRQ14": "Youssef Amyn",
    "IRQ15": "Aimar Sher",
    "IRQ16": "Marko Farji",
    "IRQ17": "Osama Rashid",
    "IRQ18": "Ali Al-Hamadi",
    "IRQ19": "Aymen Hussein",
    "IRQ20": "Mohanad Ali",
    # ── Jordan (JOR) ────────────────────────────────────────────────────────
    "JOR1":  "Escudo FOIL",
    "JOR2":  "Yazeed Abulaila",
    "JOR3":  "Ihsan Haddad",
    "JOR4":  "Mohammad Abu Hashish",
    "JOR5":  "Yazan Al-Arab",
    "JOR6":  "Abdallah Nasib",
    "JOR7":  "Saleem Obaid",
    "JOR8":  "Mohammad Abualnadi",
    "JOR9":  "Ibrahim Saadeh",
    "JOR10": "Nizar Al-Rashdan",
    "JOR11": "Noor Al-Rawabdeh",
    "JOR12": "Mohannad Abu Taha",
    "JOR13": "Foto do Time",
    "JOR14": "Amer Jamous",
    "JOR15": "Musa Al-Taamari",
    "JOR16": "Yazan Al-Naimat",
    "JOR17": "Mahmoud Al-Mardi",
    "JOR18": "Ali Olwan",
    "JOR19": "Mohammad Abu Zrayq",
    "JOR20": "Ibrahim Sabra",
    # ── Japan (JPN) ─────────────────────────────────────────────────────────
    "JPN1":  "Escudo FOIL",
    "JPN2":  "Zion Suzuki",
    "JPN3":  "Henry Hiroki Mochizuki",
    "JPN4":  "Ayumu Seko",
    "JPN5":  "Junnosuke Suzuki",
    "JPN6":  "Shogo Taniguchi",
    "JPN7":  "Tsuyoshi Watanabe",
    "JPN8":  "Kaishū Sano",
    "JPN9":  "Yuki Soma",
    "JPN10": "Ao Tanaka",
    "JPN11": "Daichi Kamada",
    "JPN12": "Takefusa Kubo",
    "JPN13": "Foto do Time",
    "JPN14": "Ritsu Dōan",
    "JPN15": "Keito Nakamura",
    "JPN16": "Takumi Minamino",
    "JPN17": "Shuto Machino",
    "JPN18": "Junya Ito",
    "JPN19": "Kōki Ogawa",
    "JPN20": "Ayase Ueda",
    # ── South Korea (KOR) ───────────────────────────────────────────────────
    "KOR1":  "Escudo FOIL",
    "KOR2":  "Jo Hyeon-woo",
    "KOR3":  "Kim Seung-gyu",
    "KOR4":  "Kim Min-jae",
    "KOR5":  "Cho Yu-min",
    "KOR6":  "Seol Young-woo",
    "KOR7":  "Lee Han-beom",
    "KOR8":  "Lee Tae-seok",
    "KOR9":  "Lee Myung-jae",
    "KOR10": "Lee Jae-sung",
    "KOR11": "Hwang In-beom",
    "KOR12": "Lee Kang-in",
    "KOR13": "Foto do Time",
    "KOR14": "Paik Seung-ho",
    "KOR15": "Jens Castrop",
    "KOR16": "Lee Dong-gyeong",
    "KOR17": "Cho Gue-sung",
    "KOR18": "Son Heung-min",
    "KOR19": "Hwang Hee-chan",
    "KOR20": "Oh Hyeon-gyu",
    # ── Saudi Arabia (KSA) ──────────────────────────────────────────────────
    "KSA1":  "Escudo FOIL",
    "KSA2":  "Nawaf Al-Aqidi",
    "KSA3":  "Abdulrahman Al-Sanbi",
    "KSA4":  "Saud Abdulhamid",
    "KSA5":  "Nawaf Boushal",
    "KSA6":  "Jihad Al-Thakri",
    "KSA7":  "Moteb Al-Harbi",
    "KSA8":  "Hassan Altambakti",
    "KSA9":  "Musab Al-Juwayr",
    "KSA10": "Ziyad Al-Johani",
    "KSA11": "Abdullah Al-Khaibari",
    "KSA12": "Nasser Al-Dawsari",
    "KSA13": "Foto do Time",
    "KSA14": "Saleh Abu Alshamat",
    "KSA15": "Marwan Al-Sahafi",
    "KSA16": "Salem Al-Dawsari",
    "KSA17": "Abdulrahman Al-Aboud",
    "KSA18": "Feras Akbrikan",
    "KSA19": "Saleh Al-Shehri",
    "KSA20": "Abdullah Al-Hamdan",
    # ── Morocco (MAR) ───────────────────────────────────────────────────────
    "MAR1":  "Escudo FOIL",
    "MAR2":  "Yassine Bounou",
    "MAR3":  "Munir El Kajoui",
    "MAR4":  "Achraf Hakimi",
    "MAR5":  "Noussair Mazraoui",
    "MAR6":  "Nayef Aguerd",
    "MAR7":  "Romain Saïss",
    "MAR8":  "Jawad El Yamiq",
    "MAR9":  "Adam Masina",
    "MAR10": "Sofyan Amrabat",
    "MAR11": "Azzedine Ounahi",
    "MAR12": "Eliesse Ben Seghir",
    "MAR13": "Foto do Time",
    "MAR14": "Bilal El Khannouss",
    "MAR15": "Ismaël Saibari",
    "MAR16": "Youssef En-Nesyri",
    "MAR17": "Abde Ezzalzouli",
    "MAR18": "Soufiane Rahimi",
    "MAR19": "Brahim Díaz",
    "MAR20": "Ayoub El Kaabi",
    # ── Mexico (MEX) ────────────────────────────────────────────────────────
    "MEX1":  "Escudo FOIL",
    "MEX2":  "Luis Malagón",
    "MEX3":  "Johan Vásquez",
    "MEX4":  "Jorge Sánchez",
    "MEX5":  "César Montes",
    "MEX6":  "Jesús Gallardo",
    "MEX7":  "Israel Reyes",
    "MEX8":  "Diego Lainez",
    "MEX9":  "Carlos Rodríguez",
    "MEX10": "Edson Álvarez",
    "MEX11": "Orbelín Pineda",
    "MEX12": "Marcel Ruiz",
    "MEX13": "Foto do Time",
    "MEX14": "Érick Sánchez",
    "MEX15": "Hirving Lozano",
    "MEX16": "Santiago Giménez",
    "MEX17": "Raúl Jiménez",
    "MEX18": "Alexis Vega",
    "MEX19": "Roberto Alvarado",
    "MEX20": "César Huerta",
    # ── Netherlands (NED) ───────────────────────────────────────────────────
    "NED1":  "Escudo FOIL",
    "NED2":  "Bart Verbruggen",
    "NED3":  "Virgil van Dijk",
    "NED4":  "Micky van de Ven",
    "NED5":  "Jurriën Timber",
    "NED6":  "Denzel Dumfries",
    "NED7":  "Nathan Aké",
    "NED8":  "Jeremie Frimpong",
    "NED9":  "Jan Paul van Hecke",
    "NED10": "Tijjani Reijnders",
    "NED11": "Ryan Gravenberch",
    "NED12": "Teun Koopmeiners",
    "NED13": "Foto do Time",
    "NED14": "Frenkie de Jong",
    "NED15": "Xavi Simons",
    "NED16": "Justin Kluivert",
    "NED17": "Memphis Depay",
    "NED18": "Donyell Malen",
    "NED19": "Wout Weghorst",
    "NED20": "Cody Gakpo",
    # ── Norway (NOR) ────────────────────────────────────────────────────────
    "NOR1":  "Escudo FOIL",
    "NOR2":  "Ørjan Nyland",
    "NOR3":  "Julian Ryerson",
    "NOR4":  "Leo Østigård",
    "NOR5":  "Kristoffer Ajer",
    "NOR6":  "Marcus Holmgren Pedersen",
    "NOR7":  "David Møller Wolfe",
    "NOR8":  "Torbjørn Heggem",
    "NOR9":  "Morten Thorsby",
    "NOR10": "Martin Ødegaard",
    "NOR11": "Sander Berge",
    "NOR12": "Andreas Schjelderup",
    "NOR13": "Foto do Time",
    "NOR14": "Patrick Berg",
    "NOR15": "Erling Haaland",
    "NOR16": "Alexander Sørloth",
    "NOR17": "Aron Dønnum",
    "NOR18": "Jørgen Strand Larsen",
    "NOR19": "Antonio Nusa",
    "NOR20": "Oscar Bobb",
    # ── New Zealand (NZL) ───────────────────────────────────────────────────
    "NZL1":  "Escudo FOIL",
    "NZL2":  "Max Crocombe",
    "NZL3":  "Alex Paulsen",
    "NZL4":  "Michael Boxall",
    "NZL5":  "Liberato Cacace",
    "NZL6":  "Tim Payne",
    "NZL7":  "Tyler Bindon",
    "NZL8":  "Francis de Vries",
    "NZL9":  "Finn Surman",
    "NZL10": "Joe Bell",
    "NZL11": "Sarpreet Singh",
    "NZL12": "Ryan Thomas",
    "NZL13": "Foto do Time",
    "NZL14": "Matthew Garbett",
    "NZL15": "Marko Stamenić",
    "NZL16": "Ben Old",
    "NZL17": "Chris Wood",
    "NZL18": "Elijah Just",
    "NZL19": "Callum McCowatt",
    "NZL20": "Kosta Barbarouses",
    # ── Panama (PAN) ────────────────────────────────────────────────────────
    "PAN1":  "Escudo FOIL",
    "PAN2":  "Orlando Mosquera",
    "PAN3":  "Luis Mejía",
    "PAN4":  "Fidel Escobar",
    "PAN5":  "Andrés Andrade",
    "PAN6":  "Michael Amir Murillo",
    "PAN7":  "Eric Davis",
    "PAN8":  "José Córdoba",
    "PAN9":  "César Blackman",
    "PAN10": "Cristian Martínez",
    "PAN11": "Aníbal Godoy",
    "PAN12": "Adalberto Carrasquilla",
    "PAN13": "Foto do Time",
    "PAN14": "Édgar Bárcenas",
    "PAN15": "Carlos Harvey",
    "PAN16": "Ismael Díaz",
    "PAN17": "José Fajardo",
    "PAN18": "Cecilio Waterman",
    "PAN19": "José Luiz Rodríguez",
    "PAN20": "Alberto Quintero",
    # ── Paraguay (PAR) ──────────────────────────────────────────────────────
    "PAR1":  "Escudo FOIL",
    "PAR2":  "Roberto Fernández",
    "PAR3":  "Orlando Gill",
    "PAR4":  "Gustavo Gómez",
    "PAR5":  "Fabián Balbuena",
    "PAR6":  "Juan José Cáceres",
    "PAR7":  "Omar Alderete",
    "PAR8":  "Junior Alonso",
    "PAR9":  "Mathías Villasanti",
    "PAR10": "Diego Gómez",
    "PAR11": "Damián Bobadilla",
    "PAR12": "Andrés Cubas",
    "PAR13": "Foto do Time",
    "PAR14": "Matías Galarza",
    "PAR15": "Julio Enciso",
    "PAR16": "Alejandro Romero Gamarra",
    "PAR17": "Miguel Almirón",
    "PAR18": "Ramón Sosa",
    "PAR19": "Ángel Romero",
    "PAR20": "Antonio Sanabria",
    # ── Portugal (POR) ──────────────────────────────────────────────────────
    "POR1":  "Escudo FOIL",
    "POR2":  "Diogo Costa",
    "POR3":  "José Sá",
    "POR4":  "Rúben Dias",
    "POR5":  "João Cancelo",
    "POR6":  "Diogo Dalot",
    "POR7":  "Nuno Mendes",
    "POR8":  "Gonçalo Inácio",
    "POR9":  "Bernardo Silva",
    "POR10": "Bruno Fernandes",
    "POR11": "Rúben Neves",
    "POR12": "Vitinha",
    "POR13": "Foto do Time",
    "POR14": "João Neves",
    "POR15": "Cristiano Ronaldo",
    "POR16": "Francisco Trincão",
    "POR17": "João Félix",
    "POR18": "Gonçalo Ramos",
    "POR19": "Pedro Neto",
    "POR20": "Rafael Leão",
    # ── Qatar (QAT) ─────────────────────────────────────────────────────────
    "QAT1":  "Escudo FOIL",
    "QAT2":  "Meshaal Barsham",
    "QAT3":  "Sultan Al-Brake",
    "QAT4":  "Lucas Mendes",
    "QAT5":  "Homam Ahmed",
    "QAT6":  "Boualem Khoukhi",
    "QAT7":  "Pedro Miguel",
    "QAT8":  "Tarek Salman",
    "QAT9":  "Mohamed Al-Mannai",
    "QAT10": "Karim Boudiaf",
    "QAT11": "Assim Madibo",
    "QAT12": "Ahmed Fathi",
    "QAT13": "Foto do Time",
    "QAT14": "Mohammed Waad",
    "QAT15": "Abdulaziz Hatem",
    "QAT16": "Hassan Al-Haydos",
    "QAT17": "Edmilson Junior",
    "QAT18": "Akram Afif",
    "QAT19": "Ahmed Al-Ganehi",
    "QAT20": "Almoez Ali",
    # ── South Africa (RSA) ──────────────────────────────────────────────────
    "RSA1":  "Escudo FOIL",
    "RSA2":  "Ronwen Williams",
    "RSA3":  "Sipho Chaine",
    "RSA4":  "Aubrey Modiba",
    "RSA5":  "Samukele Kabini",
    "RSA6":  "Mbekezeli Mbokazi",
    "RSA7":  "Khulumani Ndamane",
    "RSA8":  "Siyabonga Ngezana",
    "RSA9":  "Khuliso Mudau",
    "RSA10": "Nkosinathi Sibisi",
    "RSA11": "Teboho Mokoena",
    "RSA12": "Thalente Mbatha",
    "RSA13": "Foto do Time",
    "RSA14": "Bathasi Aubaas",
    "RSA15": "Yaya Sithole",
    "RSA16": "Sipho Mbule",
    "RSA17": "Lyle Foster",
    "RSA18": "Iqraam Rayners",
    "RSA19": "Mohau Nkota",
    "RSA20": "Oswin Appollis",
    # ── Scotland (SCO) ──────────────────────────────────────────────────────
    "SCO1":  "Escudo FOIL",
    "SCO2":  "Angus Gunn",
    "SCO3":  "Jack Hendry",
    "SCO4":  "Kieran Tierney",
    "SCO5":  "Aaron Hickey",
    "SCO6":  "Andrew Robertson",
    "SCO7":  "Scott McKenna",
    "SCO8":  "John Souttar",
    "SCO9":  "Anthony Ralston",
    "SCO10": "Grant Hanley",
    "SCO11": "Scott McTominay",
    "SCO12": "Billy Gilmour",
    "SCO13": "Foto do Time",
    "SCO14": "Lewis Ferguson",
    "SCO15": "Ryan Christie",
    "SCO16": "Kenny McLean",
    "SCO17": "John McGinn",
    "SCO18": "Lyndon Dykes",
    "SCO19": "Che Adams",
    "SCO20": "Ben Doak",
    # ── Senegal (SEN) ───────────────────────────────────────────────────────
    "SEN1":  "Escudo FOIL",
    "SEN2":  "Edouard Mendy",
    "SEN3":  "Yehvann Diouf",
    "SEN4":  "Moussa Niakhaté",
    "SEN5":  "Abdoulaye Seck",
    "SEN6":  "Ismail Jakobs",
    "SEN7":  "El Hadji Malick Diouf",
    "SEN8":  "Kalidou Koulibaly",
    "SEN9":  "Idrissa Gana Guèye",
    "SEN10": "Pape Matar Sarr",
    "SEN11": "Pape Guèye",
    "SEN12": "Habib Diarra",
    "SEN13": "Foto do Time",
    "SEN14": "Lamine Camara",
    "SEN15": "Sadio Mané",
    "SEN16": "Ismaïla Sarr",
    "SEN17": "Boulaye Dia",
    "SEN18": "Iliman Ndiaye",
    "SEN19": "Nicolas Jackson",
    "SEN20": "Krepin Diatta",
    # ── Switzerland (SUI) ───────────────────────────────────────────────────
    "SUI1":  "Escudo FOIL",
    "SUI2":  "Gregor Kobel",
    "SUI3":  "Yvon Mvogo",
    "SUI4":  "Manuel Akanji",
    "SUI5":  "Ricardo Rodríguez",
    "SUI6":  "Nico Elvedi",
    "SUI7":  "Aurèle Amenda",
    "SUI8":  "Silvan Widmer",
    "SUI9":  "Granit Xhaka",
    "SUI10": "Denis Zakaria",
    "SUI11": "Remo Freuler",
    "SUI12": "Fabian Rieder",
    "SUI13": "Foto do Time",
    "SUI14": "Ardon Jashari",
    "SUI15": "Johan Manzambi",
    "SUI16": "Michel Aebischer",
    "SUI17": "Breel Embolo",
    "SUI18": "Ruben Vargas",
    "SUI19": "Dan Ndoye",
    "SUI20": "Zeki Amdouni",
    # ── Sweden (SWE) ────────────────────────────────────────────────────────
    "SWE1":  "Escudo FOIL",
    "SWE2":  "Victor Johansson",
    "SWE3":  "Isak Hien",
    "SWE4":  "Gabriel Gudmundsson",
    "SWE5":  "Emil Holm",
    "SWE6":  "Victor Nilsson Lindelöf",
    "SWE7":  "Gustaf Lagerbielke",
    "SWE8":  "Lucas Bergvall",
    "SWE9":  "Hugo Larsson",
    "SWE10": "Jesper Karlström",
    "SWE11": "Yasin Ayari",
    "SWE12": "Mattias Svanberg",
    "SWE13": "Foto do Time",
    "SWE14": "Daniel Svensson",
    "SWE15": "Ken Sema",
    "SWE16": "Roony Bardghji",
    "SWE17": "Dejan Kulusevski",
    "SWE18": "Anthony Elanga",
    "SWE19": "Alexander Isak",
    "SWE20": "Viktor Gyökeres",
    # ── Tunisia (TUN) ───────────────────────────────────────────────────────
    "TUN1":  "Escudo FOIL",
    "TUN2":  "Bechir Ben Said",
    "TUN3":  "Aymen Dahmen",
    "TUN4":  "Yan Valery",
    "TUN5":  "Montassar Talbi",
    "TUN6":  "Yassine Meriah",
    "TUN7":  "Ali Abdi",
    "TUN8":  "Dylan Bronn",
    "TUN9":  "Ellyes Skhiri",
    "TUN10": "Aissa Laidouni",
    "TUN11": "Ferjani Sassi",
    "TUN12": "Mohamed Ali Ben Romdhane",
    "TUN13": "Foto do Time",
    "TUN14": "Hannibal Mejbri",
    "TUN15": "Elias Achouri",
    "TUN16": "Elias Saad",
    "TUN17": "Hazem Mastouri",
    "TUN18": "Ismael Gharbi",
    "TUN19": "Sayfallah Ltaief",
    "TUN20": "Naim Sliti",
    # ── Türkiye (TUR) ───────────────────────────────────────────────────────
    "TUR1":  "Escudo FOIL",
    "TUR2":  "Uğurcan Çakır",
    "TUR3":  "Mert Müldür",
    "TUR4":  "Zeki Çelik",
    "TUR5":  "Abdülkerim Bardakcı",
    "TUR6":  "Çağlar Söyüncü",
    "TUR7":  "Merih Demiral",
    "TUR8":  "Ferdi Kadıoğlu",
    "TUR9":  "Kaan Ayhan",
    "TUR10": "İsmail Yüksek",
    "TUR11": "Hakan Çalhanoğlu",
    "TUR12": "Orkun Kökçü",
    "TUR13": "Foto do Time",
    "TUR14": "Arda Güler",
    "TUR15": "İrfan Can Kahveci",
    "TUR16": "Yunus Akgün",
    "TUR17": "Can Uzun",
    "TUR18": "Barış Alper Yılmaz",
    "TUR19": "Kerem Aktürkoğlu",
    "TUR20": "Kenan Yıldız",
    # ── Uruguay (URU) ───────────────────────────────────────────────────────
    "URU1":  "Escudo FOIL",
    "URU2":  "Sergio Rochet",
    "URU3":  "Santiago Mele",
    "URU4":  "Ronald Araújo",
    "URU5":  "José María Giménez",
    "URU6":  "Sebastián Cáceres",
    "URU7":  "Mathías Olivera",
    "URU8":  "Guillermo Varela",
    "URU9":  "Nahitan Nández",
    "URU10": "Federico Valverde",
    "URU11": "Giorgian De Arrascaeta",
    "URU12": "Rodrigo Bentancur",
    "URU13": "Foto do Time",
    "URU14": "Manuel Ugarte",
    "URU15": "Nicolás de la Cruz",
    "URU16": "Maxi Araújo",
    "URU17": "Darwin Núñez",
    "URU18": "Federico Viñas",
    "URU19": "Rodrigo Aguirre",
    "URU20": "Facundo Pellistri",
    # ── USA ─────────────────────────────────────────────────────────────────
    "USA1":  "Escudo FOIL",
    "USA2":  "Matt Freese",
    "USA3":  "Chris Richards",
    "USA4":  "Tim Ream",
    "USA5":  "Mark McKenzie",
    "USA6":  "Alex Freeman",
    "USA7":  "Antonee Robinson",
    "USA8":  "Tyler Adams",
    "USA9":  "Tanner Tessmann",
    "USA10": "Weston McKennie",
    "USA11": "Christian Roldan",
    "USA12": "Timothy Weah",
    "USA13": "Foto do Time",
    "USA14": "Diego Luna",
    "USA15": "Malik Tillman",
    "USA16": "Christian Pulisic",
    "USA17": "Brenden Aaronson",
    "USA18": "Ricardo Pepi",
    "USA19": "Haji Wright",
    "USA20": "Folarin Balogun",
    # ── Uzbekistan (UZB) ────────────────────────────────────────────────────
    "UZB1":  "Escudo FOIL",
    "UZB2":  "Utkir Yusupov",
    "UZB3":  "Farrukh Sayfiev",
    "UZB4":  "Sherzod Nasrullaev",
    "UZB5":  "Umar Eshmurodov",
    "UZB6":  "Husniddin Aliqulov",
    "UZB7":  "Rustamjon Ashurmatov",
    "UZB8":  "Khojiakbar Alijonov",
    "UZB9":  "Abdukodir Khusanov",
    "UZB10": "Odiljon Hamrobekov",
    "UZB11": "Otabek Shukurov",
    "UZB12": "Jamshid Iskanderov",
    "UZB13": "Foto do Time",
    "UZB14": "Azizbek Turgunboev",
    "UZB15": "Khojimat Erkinov",
    "UZB16": "Eldor Shomurodov",
    "UZB17": "Oston Urunov",
    "UZB18": "Jaloliddin Masharipov",
    "UZB19": "Igor Sergeev",
    "UZB20": "Abbosbek Fayzullaev",
}


def atualizar_csv():
    csv_path = os.path.join(BASE, "album.csv")
    rows = []
    atualizados = 0
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    for row in rows:
        codigo = row["Codigo"].strip()
        if codigo in DESCRICOES:
            row["Descricao"] = DESCRICOES[codigo]
            atualizados += 1

    with open(csv_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=["Codigo", "Secao", "Descricao", "Status", "Repetidas"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"CSV atualizado: {atualizados}/{len(rows)} descrições preenchidas.")
    return rows


def atualizar_sheet(rows):
    sa_path = os.path.join(BASE, "service_account.json")
    cfg_path = os.path.join(BASE, "sheet_config.json")
    if not os.path.exists(sa_path) or not os.path.exists(cfg_path):
        print("service_account.json ou sheet_config.json não encontrado — pulando atualização da planilha.")
        return

    import gspread
    with open(sa_path) as f:
        creds_info = json.load(f)
    with open(cfg_path) as f:
        sheet_id = json.load(f)["sheet_id"]

    gc = gspread.service_account_from_dict(creds_info)
    ws = gc.open_by_key(sheet_id).sheet1

    # Atualiza apenas coluna 3 (Descricao) — preserva Status e Repetidas
    cells = []
    for i, row in enumerate(rows):
        codigo = row["Codigo"].strip()
        if codigo in DESCRICOES:
            sheet_row = i + 2  # linha 1 = cabeçalho
            cells.append(gspread.Cell(sheet_row, 3, DESCRICOES[codigo]))

    if cells:
        ws.update_cells(cells, value_input_option="RAW")
        print(f"Planilha atualizada: {len(cells)} células na coluna Descricao.")
    else:
        print("Nenhuma célula atualizada na planilha.")


def main():
    print("Atualizando descrições...")
    rows = atualizar_csv()
    atualizar_sheet(rows)
    print("Concluído!")


if __name__ == "__main__":
    main()
